# Generated by Django 4.2.7 on 2023-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_main_img',
            field=models.ImageField(default=False, upload_to='C:\\Users\\jadam\\njit-web-developement\\Instruments-NJIT\\instruments_njit_web\\staticimgs/'),
        ),
    ]
