# Generated by Django 4.2.7 on 2023-12-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=False, max_length=254)),
                ('address', models.TextField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('credit_card_number', models.CharField(default=False, max_length=16)),
                ('expiration_date', models.DateField(default=False)),
                ('cvv', models.CharField(default=False, max_length=4)),
            ],
        ),
    ]
