# Generated by Django 4.2.7 on 2023-12-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_url_alias_alter_item_item_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='url_alias',
            new_name='slug',
        ),
    ]
